version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Post build command done
artifacts:
  files:
    - '**/*'
  base-directory: files
  secondary-artifacts:
    mysecondartifact:
      base-directory: files
      files:
        - '**/*'